### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by Sha3-git** [meklitAlemu/ENSE374_Troi#13]
Creating a landing page for our users

**Comment by Sha3-git** [comment]
So new features that leans more into our MVP 2.
Implementing a log in and sign up.
These would also have a remember me and a possible forgot password function.
The benefits are that we can easily attach shoes to a users who already used our mvp 1 so that we can scale our site functionality towards a saved shoe page.

**Comment by meklitAlemu** [comment]
This user account feature also comes with benefits like retaining user data and recommendation. If we get to MPV3, with forums and tool tips that connect and educate the running community, it's easier to do so with user accounts.

**Comment by Sha3-git** [comment]
I think out Home page can be better modified to give first time users a better idea of our website's purpose. A small introduction blurb would be beneficial.

**Comment by Sha3-git** [comment]
Home page gives users a good understanding of our site's purpose
