### ISSUE TITLE
Create Terrain Page

### ISSUE THREAD

**Issue by Sha3-git** [meklitAlemu/ENSE374_Troi#15]
If we can implement this then the rest of the pages will follow as they all utilize the same functionality.
The terrain page should have the terrain options, tooltips and footer title.

**Comment by Sha3-git** [comment]
Not mobile responsive

**Comment by Sha3-git** [comment]
Footer for the page still needs to be created  but it is now semi mobile responsive

**Comment by meklitAlemu** [comment]
The page implementation can have basic functionality to get  general website flow and layout. We can look into updating the UI from simple options to responsive cards later on.

**Comment by Sha3-git** [comment]
Replace ui with modified cards as per mvp 2
