### ISSUE TITLE
Create Price Page

### ISSUE THREAD

**Issue by Sha3-git** [meklitAlemu/ENSE374_Troi#18]
A page for users to choose various price increments to choose from

**Comment by meklitAlemu** [comment]
So far all shoes fall between 50-350 range. So shoes will be recommended if price is <= user selected price

**Comment by meklitAlemu** [comment]
We have two methods of implementing this, an adjustable scale where we recommend shoes <= chosen price. Other option is radio buttons that group price range in categories. Ex: 50 - 100, 100 - 150, 150 - 200, 200 - 250, 250+

**Comment by Sha3-git** [comment]
ok got it! 
I will prioritize implementing a price page with an adjustable scale for the users
plan b will be our radio buttons.

**Comment by Sha3-git** [comment]
Price page UI still needs to be fixed. It currently doesn't perform well on anything lower than a desktop screen and is compressed on laptop screens

**Comment by Sha3-git** [comment]
Price page is dysfunctional on the desktop
