### ISSUE TITLE
Create a shoe database with appropriate shoe types

### ISSUE THREAD

**Issue by Sha3-git** [meklitAlemu/ENSE374_Troi#23]
Populating our database with shoe products based on our uml data diagrams

**Comment by Sha3-git** [comment]
was able to scrape some shoe data from a website but tags such as cushioning, heel drop and so on were not found yet. Do we edit these manually (spend a whole day just populating with added tags) or keep looking on the website to find how they're storing these tags.

**Comment by Sha3-git** [comment]
this is what the data looks like so far
![image](https://user-images.githubusercontent.com/87103205/201537629-66753b26-4154-4987-9737-8f054bdd1c1f.png)

**Comment by meklitAlemu** [comment]
I've taken up this task. At the moment, I've compiled the data to populate shoes for "road" terrain. We have 10+ shoes in this category. I'm looking into compiling data for "trail" then "gravel" terrain.

**Comment by meklitAlemu** [comment]
Project database changes I made

- on terrain category: road is 0, trail is 1, gravel is 2
- There's no barefoot option for gravel, because this terrain type always needs footwear with cushion

**Comment by Sha3-git** [comment]
Currently missing the image parameters in database 
@meklitAlemu

**Comment by meklitAlemu** [comment]
Added image parameter to shoes collections. Populated the remaining collections as well

**Comment by Sha3-git** [comment]
MVP2 will feature more shoes
